name: Java CI with Gradle

on:
 workflow_call:
  inputs:
    version:
      required: true
      type: string

env:
  REGISTRY: mauron
  SONAR_HOST_URL: http://localhost:900

jobs:
  ci:

    #runs-on: ubuntu-latest
    runs-on: profe

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.version }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn package

    - name: Buscar jar
      run: |
        ls -al target/*.jar
   
    
    - name: sonarqube
      run: |
        echo "Run SonarQube analysis manually..."
        mvn clean verify sonar:sonar \
            -Dsonar.projectKey=${{ github.event.repository.name }} \
            -Dsonar.projectName=${{ github.event.repository.name }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}


    - name: build image
      run: |
        echo "Building Docker image..."
        docker build -t ${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ github.run_number}} .

    - name: login docker
      run: |
        echo "Logging in to Docker..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        echo "Pushing Docker image..."
        docker push ${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ github.run_number}}


